// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("CodeQuality", "IDE0079:Remove unnecessary suppression", Scope = "namespaceanddescendants", Target = "~N:XLAuth", Justification = "<Pending>")]

#if DEBUG
[assembly: SuppressMessage("Code smell", "BCC4009:Catch should do more than rethrow", Scope = "member", Target = "~M:XLAuth.Support.LogInit.Setup(System.String,System.String[])", Justification = "Only when debugging.")]
[assembly: SuppressMessage("Compiler Warning", "CS0067:An event was declared but never used in the class in which it was declared.", Scope = "member", Target = "~E:XLAuth.Update.Updates.UpdateCheckFinished", MessageId = "Updates.UpdateCheckFinished", Justification = "Only when debugging.")]
#else
#endif

// TODO: Wait for the issue to be fixed: https://github.com/meziantou/Meziantou.Analyzer/issues/775
[assembly: SuppressMessage("Design", "MA0083:ConstructorArgument parameters should exist in constructors", Scope = "member", Target = "~P:XLAuth.Resources.PackIconExtension.Size", MessageId = "size")]

[assembly: SuppressMessage("Design", "MA0048:File name must match type name", Scope = "type", Target = "~T:DotEnv.Generated.Environment", Justification = "Generated Code")]
[assembly: SuppressMessage("Code smell", "BCC4006:Methods should not have too many return statements", Scope = "member", Target = "~M:XLAuth.Support.Logger.GetMicrosoftContext(System.Int32)~Microsoft.Extensions.Logging.ILogger", Justification = "Required")]
[assembly: SuppressMessage("Code smell", "BCC4006:Methods should not have too many return statements", Scope = "member", Target = "~M:XLAuth.Config.AccountManager.SendOTPKeyAsync(System.String)~System.Threading.Tasks.Task{System.ValueTuple{XLAuth.Domain.OTPKeyResponse,System.Exception}}", Justification = "Required")]
[assembly: SuppressMessage("Design", "MA0051:Method is too long", Scope = "member", Target = "~M:XLAuth.App.OnStartup(System.Object,System.Windows.StartupEventArgs)", Justification = "Startup methods should be heavy.")]
[assembly: SuppressMessage("Design", "MA0051:Method is too long", Scope = "member", Target = "~M:XLAuth.Models.ViewModel.SettingsControlViewModel.UpdatePopupContent", Justification = "This is heavy I know.")]
[assembly: SuppressMessage("Good practice", "BCC3001:Class can't be static", Scope = "type", Target = "~T:DotEnv.Generated.Environment", Justification = "Utility Class")]
[assembly: SuppressMessage("Good practice", "BCC3001:Class can't be static", Scope = "type", Target = "~T:XLAuth.Config.EnvironmentSettings", Justification = "Utility Class")]
[assembly: SuppressMessage("Good practice", "BCC3001:Class can't be static", Scope = "type", Target = "~T:XLAuth.Paths", Justification = "Utility Class")]
[assembly: SuppressMessage("Good practice", "BCC3001:Class can't be static", Scope = "type", Target = "~T:XLAuth.Support.ArgumentParser", Justification = "Utility Class")]
[assembly: SuppressMessage("Good practice", "BCC3001:Class can't be static", Scope = "type", Target = "~T:XLAuth.Support.LogInit", Justification = "Utility Class")]
[assembly: SuppressMessage("Good practice", "BCC3001:Class can't be static", Scope = "type", Target = "~T:XLAuth.Support.Util", Justification = "Utility Class")]
[assembly: SuppressMessage("Good practice", "BCC3007:The name is too long.", Scope = "member", Target = "~F:XLAuth.Models.ViewModel.SettingsControlViewModel._accountSelectionButtonActualWidth", Justification = "This is descriptive")]
[assembly: SuppressMessage("Good practice", "BCC3007:The name is too long.", Scope = "member", Target = "~F:XLAuth.Models.ViewModel.UpdateLoadingWindowViewModel._UPDATE_LOADING_CARD_HEIGHT_DEFAULT", Justification = "This is descriptive")]
[assembly: SuppressMessage("Good practice", "BCC3007:The name is too long.", Scope = "member", Target = "~M:XLAuth.Models.ViewModel.MainControlViewModel.SendTOTPAsync~System.Threading.Tasks.Task", MessageId = "ArgumentOutOfRangeException", Justification = "Built in type")]
[assembly: SuppressMessage("Good practice", "BCC3007:The name is too long.", Scope = "member", Target = "~M:XLAuth.Models.ViewModel.SettingsControlViewModel.AccountManager_OnAccountSwitched(System.Object,XLAuth.Models.Events.AccountSwitchedEventArgs)", Justification = "This is descriptive")]
[assembly: SuppressMessage("Good practice", "BCC3007:The name is too long.", Scope = "member", Target = "~M:XLAuth.Models.ViewModel.SettingsControlViewModel.AccountManager_OnReloadTriggered(System.Object,System.EventArgs)", Justification = "This is descriptive")]
[assembly: SuppressMessage("Good practice", "BCC3007:The name is too long.", Scope = "member", Target = "~M:XLAuth.Models.ViewModel.SettingsControlViewModel.AccountSelectionButtonActualWidth_SizeChanged(System.Object,System.Windows.SizeChangedEventArgs)", Justification = "This is descriptive")]
[assembly: SuppressMessage("Good practice", "BCC3007:The name is too long.", Scope = "member", Target = "~M:XLAuth.Models.ViewModel.SettingsControlViewModel.GridActualHeight_SizeChanged(System.Object,System.Windows.SizeChangedEventArgs)", Justification = "This is descriptive")]
[assembly: SuppressMessage("Good practice", "BCC3007:The name is too long.", Scope = "member", Target = "~M:XLAuth.Models.ViewModel.SettingsControlViewModel.ReleaseUnmanagedResources", MessageId = "AccountSelectionButtonActualWidth_SizeChanged", Justification = "This is descriptive")]
[assembly: SuppressMessage("Good practice", "BCC3007:The name is too long.", Scope = "member", Target = "~M:XLAuth.Models.ViewModel.SettingsControlViewModel.ReleaseUnmanagedResources", MessageId = "GridActualHeight_SizeChanged", Justification = "This is descriptive")]
[assembly: SuppressMessage("Good practice", "BCC3007:The name is too long.", Scope = "member", Target = "~M:XLAuth.Update.Updates.RunAsync(System.Boolean,XLAuth.Windows.ChangelogWindow)~System.Threading.Tasks.Task", MessageId = "OnChangeLogWindowClosedWrapper", Justification = "Built in type")]
[assembly: SuppressMessage("Good practice", "BCC3007:The name is too long.", Scope = "member", Target = "~M:XLAuth.Windows.CustomMessageBox.Builder.ShowAssumingDispatcherThread()~System.Windows.MessageBoxResult", Justification = "This is descriptive")]
[assembly: SuppressMessage("Good practice", "BCC3007:The name is too long.", Scope = "member", Target = "~M:XLAuth.Windows.CustomMessageBox.Builder.WithAppendSettingsDescription(System.String)~XLAuth.Windows.CustomMessageBox.Builder", Justification = "This is descriptive")]
[assembly: SuppressMessage("Good practice", "BCC3007:The name is too long.", Scope = "member", Target = "~P:XLAuth.Models.ViewModel.SettingsControlViewModel.AccountSelectionButtonActualWidth", Justification = "This is descriptive")]
[assembly: SuppressMessage("Good practice", "BCC3007:The name is too long.", Scope = "member", Target = "~P:XLAuth.Models.ViewModel.UpdateLoadingWindowViewModel.AutoLoginDisclaimerVisibility", Justification = "This is descriptive")]
[assembly: SuppressMessage("Good practice", "BCC3007:The name is too long.", Scope = "type", Target = "~T:XLAuth.Models.ViewModel.DeleteAccountDialogViewModel", Justification = "This is descriptive")]
[assembly: SuppressMessage("Good practice", "BCC3007:The name is too long.", Scope = "type", Target = "~T:XLAuth.Models.ViewModel.UpdateLoadingWindowViewModel", Justification = "This is descriptive")]
[assembly: SuppressMessage("Maintainability", "AV1551:Method overload should call another overload", Scope = "member", Target = "~M:XLAuth.Support.Util.GetBrush(System.String,System.Type)~System.Windows.Media.Brush")]
[assembly: SuppressMessage("Naming", "AV1704:Identifier contains one or more digits in its name", Scope = "type", Target = "~T:XLAuth.Config.AuthSettings")]
[assembly: SuppressMessage("ReSharper", "AutoPropertyCanBeMadeGetOnly.Global", Scope = "type", Target = "~T:XLAuth.App.CmdLineOptions")]
[assembly: SuppressMessage("ReSharper", "BaseObjectGetHashCodeCallInGetHashCode", Scope = "member", Target = "~M:XLAuth.Config.AuthSettings.GetHashCode()~System.Int32")]
[assembly: SuppressMessage("Single responsibility", "BCC2001:Method has many parameters", Scope = "member", Target = "~M:XLAuth.Config.Converters.GuidJsonConverter.ReadJson(Newtonsoft.Json.JsonReader,System.Type,System.Guid,System.Boolean,Newtonsoft.Json.JsonSerializer)~System.Guid", Justification = "API Call")]
[assembly: SuppressMessage("Single responsibility", "BCC2001:Method has many parameters", Scope = "member", Target = "~M:XLAuth.Config.Converters.IPAddressJsonConverter.ReadJson(Newtonsoft.Json.JsonReader,System.Type,System.Net.IPAddress,System.Boolean,Newtonsoft.Json.JsonSerializer)~System.Net.IPAddress", Justification = "API Call")]
[assembly: SuppressMessage("Single responsibility", "BCC2001:Method has many parameters", Scope = "member", Target = "~M:XLAuth.Update.Updates.FakeVelopackFileDownloader.DownloadFile(System.String,System.String,System.Action{System.Int32},System.String,System.String,System.Threading.CancellationToken)~System.Threading.Tasks.Task", Justification = "API Call")]
[assembly: SuppressMessage("Single responsibility", "BCC2001:Method has many parameters", Scope = "member", Target = "~M:XLAuth.Windows.CustomMessageBox.Show(System.String,System.String,System.Windows.MessageBoxButton,System.Windows.MessageBoxImage,System.Boolean,System.Boolean,System.Windows.Window)~System.Windows.MessageBoxResult", Justification = "This is a factory.")]
[assembly: SuppressMessage("Single responsibility", "BCC2004:Method has a lot of declaration", Scope = "member", Target = "~M:XLAuth.Models.ViewModel.SettingsControlViewModel.UpdatePopupContent", Justification = "This is heavy I know.")]
[assembly: SuppressMessage("Style", "IDE0130:Namespace does not match folder structure", Scope = "namespace", Target = "~N:XLAuth.Resources")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Scope = "member", Target = "~M:XLAuth.Domain.Commands.AsyncCommandImpl.Refresh")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Scope = "member", Target = "~M:XLAuth.Domain.Commands.AsyncCommandImpl`1.Refresh")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Scope = "member", Target = "~M:XLAuth.Domain.Commands.CommandImpl.Refresh")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Scope = "member", Target = "~M:XLAuth.Domain.Commands.CommandImpl`1.Refresh")]
[assembly: SuppressMessage("Good practice", "BCC3001:Class can't be static", Scope = "type", Target = "~T:XLAuth.Domain.Components.Helpers.NavigationCommands", Justification = "Utility Class")]
[assembly: SuppressMessage("Good practice", "BCC3001:Class can't be static", Scope = "type", Target = "~T:XLAuth.Resources.PackIconDataFactory", Justification = "Utility Class")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Scope = "type", Target = "~T:XLAuth.Domain.Components.Helpers.NavigationCommands", Justification = "Microsoft Standard")]
[assembly: SuppressMessage("ReSharper", "InconsistentNaming", Scope = "type", Target = "~T:XLAuth.Domain.Components.Helpers.NavigationCommands", Justification = "Microsoft Standard")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Scope = "member", Target = "~F:XLAuth.Resources.PackIcon.KindProperty", Justification = "Microsoft Standard")]
[assembly: SuppressMessage("ReSharper", "InconsistentNaming", Scope = "member", Target = "~F:XLAuth.Resources.PackIcon.KindProperty", Justification = "Microsoft Standard")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Scope = "member", Target = "~F:XLAuth.Resources.PackIcon.DataPropertyKey", Justification = "Microsoft Standard")]
[assembly: SuppressMessage("ReSharper", "InconsistentNaming", Scope = "member", Target = "~F:XLAuth.Resources.PackIcon.DataPropertyKey", Justification = "Microsoft Standard")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Scope = "member", Target = "~F:XLAuth.Resources.PackIcon.DataProperty", Justification = "Microsoft Standard")]
[assembly: SuppressMessage("ReSharper", "InconsistentNaming", Scope = "member", Target = "~F:XLAuth.Resources.PackIcon.DataProperty", Justification = "Microsoft Standard")]
[assembly: SuppressMessage("Good practice", "BCC3007:The name is too long.", Scope = "member", Target = "~M:XLAuth.Resources.PackIcon.KindPropertyChangedCallback(System.Windows.DependencyObject,System.Windows.DependencyPropertyChangedEventArgs)", Justification = "This is descriptive")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Scope = "member", Target = "~P:XLAuth.Models.ViewModel.AddAccountDialogViewModel.CancelAddAccountDialog", Justification = "<Pending>")]
[assembly: SuppressMessage("Good practice", "BCC3007:The name is too long.", Scope = "member", Target = "~M:XLAuth.Extensions.ExceptionExtensions.ThrowEnumOutOfRangeException``2(System.String,``1,System.String)~``0", Justification = "<Pending>")]
[assembly: SuppressMessage("Good practice", "BCC3001:Class can't be static", Scope = "type", Target = "~T:XLAuth.Extensions.ExceptionExtensions", Justification = "<Pending>")]
[assembly: SuppressMessage("Good practice", "BCC3001:Class can't be static", Scope = "type", Target = "~T:XLAuth.Extensions.LanguageExtensions", Justification = "<Pending>")]
[assembly: SuppressMessage("Good practice", "BCC3007:The name is too long.", Scope = "type", Target = "~T:XLAuth.Extensions.ResourceDictionaryExtensions", Justification = "<Pending>")]
[assembly: SuppressMessage("Good practice", "BCC3007:The name is too long.", Scope = "type", Target = "~T:XLAuth.Models.ViewModel.RenameAccountDialogViewModel", Justification = "<Pending>")]
[assembly: SuppressMessage("Good practice", "BCC3007:The name is too long.", Scope = "member", Target = "~P:XLAuth.Models.ViewModel.SettingsControlViewModel.CloseAppAfterSendingCheckBoxLabel", Justification = "<Pending>")]
[assembly: SuppressMessage("Code smell", "BCC4007:\"switch\" have a lot of \"case\" clauses", Scope = "member", Target = "~M:XLAuth.Models.ViewModel.SettingsControlViewModel.SetProperty``1(``0@,``0,System.String)~System.Boolean", Justification = "<Pending>")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Scope = "member", Target = "~P:XLAuth.Models.ViewModel.SettingsControlViewModel.CurrentAccountName", Justification = "<Pending>")]
[assembly: SuppressMessage("Good practice", "BCC3007:The name is too long.", Scope = "member", Target = "~P:XLAuth.Models.ViewModel.SettingsControlViewModel.AccountSelectionButtonContent", Justification = "<Pending>")]
[assembly: SuppressMessage("Design", "MA0051:Method is too long", Scope = "member", Target = "~M:XLAuth.Models.ViewModel.SettingsControlViewModel.SetProperty``1(``0@,``0,System.String)~System.Boolean", Justification = "80 out of 60 maximum lines, good enough.")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Scope = "member", Target = "~P:XLAuth.Models.ViewModel.SettingsControlViewModel.SwitchAccountCommand", Justification = "<Pending>")]
[assembly: SuppressMessage("Good practice", "BCC3007:The name is too long.", Scope = "member", Target = "~P:XLAuth.Windows.CustomMessageBox.Builder.OverrideTopMostFromParentWindow", Justification = "<Pending>")]
[assembly: SuppressMessage("Code smell", "BCC4007:\"switch\" have a lot of \"case\" clauses", Scope = "member", Target = "~M:XLAuth.Models.ViewModel.MainControlViewModel.SendTOTPAsync~System.Threading.Tasks.Task", Justification = "<Pending>")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Scope = "member", Target = "~P:XLAuth.Models.ViewModel.OTPKeyDialogViewModel.CancelOTPKeyDialog", Justification = "<Pending>")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Scope = "member", Target = "~P:XLAuth.Models.ViewModel.CustomMessageBoxViewModel.NoButtonLabel", Justification = "<Pending>")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Scope = "member", Target = "~P:XLAuth.Models.ViewModel.CustomMessageBoxViewModel.CancelButtonLabel", Justification = "<Pending>")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Scope = "member", Target = "~P:XLAuth.Models.ViewModel.CustomMessageBoxViewModel.ReportIssueCommand", Justification = "<Pending>")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Scope = "member", Target = "~P:XLAuth.Models.ViewModel.CustomMessageBoxViewModel.ReportIssueLabel", Justification = "<Pending>")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Scope = "member", Target = "~P:XLAuth.Models.ViewModel.CustomMessageBoxViewModel.OpenFAQCommand", Justification = "<Pending>")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Scope = "member", Target = "~P:XLAuth.Models.ViewModel.RenameAccountDialogViewModel.CancelRenameAccountDialog", Justification = "<Pending>")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Scope = "member", Target = "~P:XLAuth.Models.ViewModel.SettingsControlViewModel.CloseAppAfterSending", Justification = "<Pending>")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Scope = "member", Target = "~P:XLAuth.Models.ViewModel.LauncherIPDialogViewModel.CancelLauncherIPDialog", Justification = "<Pending>")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Scope = "member", Target = "~P:XLAuth.Models.ViewModel.ChangelogWindowViewModel.ChangelogThanksLabel", Justification = "<Pending>")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Scope = "member", Target = "~P:XLAuth.Models.ViewModel.ChangelogWindowViewModel.JoinDiscordButtonCommand", Justification = "<Pending>")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Scope = "member", Target = "~P:XLAuth.Models.ViewModel.ChangelogWindowViewModel.SendEmailButtonCommand", Justification = "<Pending>")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Scope = "member", Target = "~P:XLAuth.Models.ViewModel.CustomMessageBoxViewModel.YesButtonLabel", Justification = "<Pending>")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Scope = "member", Target = "~P:XLAuth.Models.ViewModel.CustomMessageBoxViewModel.CopyMessageTextLabel", Justification = "<Pending>")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Scope = "member", Target = "~P:XLAuth.Models.ViewModel.CustomMessageBoxViewModel.JoinDiscordButtonCommand", Justification = "<Pending>")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Scope = "member", Target = "~P:XLAuth.Models.ViewModel.CustomMessageBoxViewModel.OpenFAQLabel", Justification = "<Pending>")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Scope = "member", Target = "~P:XLAuth.Models.ViewModel.DeleteAccountDialogViewModel.SubmitDeleteAccountDialog", Justification = "<Pending>")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Scope = "member", Target = "~P:XLAuth.Models.ViewModel.DeleteAccountDialogViewModel.CancelDeleteAccountDialog", Justification = "<Pending>")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Scope = "member", Target = "~P:XLAuth.Models.ViewModel.MainControlViewModel.CurrentAccountName", Justification = "<Pending>")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Scope = "member", Target = "~P:XLAuth.Models.ViewModel.DeleteAccountDialogViewModel.CancelDeleteAccountDialog", Justification = "<Pending>")]
[assembly: SuppressMessage("Design", "MA0051:Method is too long", Scope = "member", Target = "~M:XLAuth.Update.Updates.RunAsync(System.Boolean,XLAuth.Windows.ChangelogWindow)~System.Threading.Tasks.Task", MessageId = "74", Justification = "<Pending>")]
[assembly: SuppressMessage("Good practice", "BCC3007:The name is too long.", Scope = "member", Target = "~P:XLAuth.Models.ViewModel.SettingsControlViewModel.CloseAppAfterSendingCheckBoxCommand", Justification = "<Pending>")]
[assembly: SuppressMessage("Good practice", "BCC3007:The name is too long.", Scope = "member", Target = "~F:XLAuth.Models.ViewModel.SettingsControlViewModel._accountSelectionButtonContent", Justification = "<Pending>")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Scope = "member", Target = "~P:XLAuth.Models.ViewModel.SettingsControlViewModel.SaveSettingsButtonCommand", Justification = "<Pending>")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Scope = "member", Target = "~P:XLAuth.Models.ViewModel.SettingsControlViewModel.CurrentLanguageName", Justification = "<Pending>")]
[assembly: SuppressMessage("Good practice", "BCC3007:The name is too long.", Scope = "member", Target = "~P:XLAuth.Models.ViewModel.SettingsControlViewModel.LanguageSelectionButtonContent", Justification = "<Pending>")]
[assembly: SuppressMessage("Good practice", "BCC3007:The name is too long.", Scope = "member", Target = "~F:XLAuth.Models.ViewModel.SettingsControlViewModel._languageSelectionButtonContent", Justification = "<Pending>")]
[assembly: SuppressMessage("Code smell", "BCC4005:Deeply nested code", Scope = "member", Target = "~M:XLAuth.Update.Updates.RunAsync(System.Boolean,XLAuth.Windows.ChangelogWindow)~System.Threading.Tasks.Task", Justification = "<Pending>")]
[assembly: SuppressMessage("Code smell", "BCC4007:\"switch\" have a lot of \"case\" clauses", Scope = "member", Target = "~M:XLAuth.Windows.CustomMessageBox.#ctor(XLAuth.Windows.CustomMessageBox.Builder)", Justification = "<Pending>")]
[assembly: SuppressMessage("Design", "MA0051:Method is too long", Scope = "member", Target = "~M:XLAuth.Windows.CustomMessageBox.#ctor(XLAuth.Windows.CustomMessageBox.Builder)", Justification = "<Pending>")]
[assembly: SuppressMessage("CodeQuality", "Serilog004:Constant MessageTemplate verifier", Scope = "member", Target = "~M:XLAuth.Support.Logger.ErrorDialog(System.Exception,System.String,System.Object[])", Justification = "<Pending>")]
[assembly: SuppressMessage("IDisposableAnalyzers.Correctness", "IDISP006:Implement IDisposable", Scope = "member", Target = "~P:XLAuth.Models.ViewModel.MainControlViewModel.MessageQueue", Justification = "<Pending>")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Scope = "member", Target = "~P:XLAuth.Models.ViewModel.UpdateLoadingWindowViewModel.AutoLoginDisclaimerVisibility", Justification = "<Pending>")]
[assembly: SuppressMessage("Good practice", "BCC3001:Class can't be static", Scope = "type", Target = "~T:XLAuth.Support.SupportLinks", Justification = "Utility Class")]
[assembly: SuppressMessage("Single responsibility", "BCC2003:Control Flag", Scope = "member", Target = "~M:XLAuth.Support.Logger.Dispose(System.Boolean)", MessageId = "disposing", Justification = "Standard")]
[assembly: SuppressMessage("Single responsibility", "BCC2003:Control Flag", Scope = "member", Target = "~M:XLAuth.Support.ResourceHelpers.Dispose(System.Boolean)", MessageId = "disposing", Justification = "Standard")]
[assembly: SuppressMessage("Single responsibility", "BCC2003:Control Flag", Scope = "member", Target = "~M:XLAuth.Models.Abstracts.ViewModelBase`1.Dispose(System.Boolean)", MessageId = "disposing", Justification = "Standard")]
[assembly: SuppressMessage("IDisposableAnalyzers.Correctness", "IDISP007:Don't dispose injected", Scope = "member", Target = "~M:XLAuth.Support.Singletons.Unload", Justification = "<Pending>")]
[assembly: SuppressMessage("Single responsibility", "BCC2003:Control Flag", Scope = "member", Target = "~M:XLAuth.Support.Singletons.Dispose(System.Boolean)", Justification = "<Pending>")]
[assembly: SuppressMessage("Code smell", "BCC4005:Deeply nested code", Scope = "member", Target = "~M:XLAuth.Support.Singletons.Dispose(System.Boolean)", Justification = "<Pending>")]
[assembly: SuppressMessage("Code smell", "BCC4005:Deeply nested code", Scope = "member", Target = "~M:XLAuth.Support.ResourceHelpers.Dispose(System.Boolean)", Justification = "<Pending>")]
