name: build.yml
on:
  push:
    branches:
      - master
      - dev
  label:
    types:
      - created
  pull_request:
    branches:
      - dev
    types:
      - assigned

env:
  REPO_OWNER: thakyz
  REPO_NAME:  XLAuth

jobs:
  build:
    if: false
    name: Build
    needs:
      -
